LICENSE, riscv-sbi.md
I have tried to create the SBI spec as per my knowledge and understanding RISC-V system. There may be some glaring mistakes either in language or technical content. Apologies in advance :).
As my knowledge on memory model is very limited, I have not described the memory ordering related functions. Kindly update.
Please feel free to edit/comment on anything and everything.
=> sbi-doc PR (Updated)

riscv-sbi.md
Please ignore the previous PR. For some reason, it did not diff correctly.
=> Some content updates

riscv-sbi.adoc
=> Fix the typo in IPI call.

riscv-sbi.adoc
=> Fix the return type and naming of SBI functions.

riscv-sbi.adoc
This is purely a stylistic change. By collecting more information into the tables, it is easier to visually scan the document.
=> Include more information in 'Function Listings'

riscv-sbi.adoc
=> Fix the my name and email address.

riscv-sbi.adoc
Reserve extension space for firmware code base specific SBI extensions.
=> Firmware Code Base SBI Extension space

riscv-sbi.adoc
Discussions: https://lists.riscv.org/g/tech-unixplatformspec/message/338
=> Add RustSBI to implementation ID list

riscv-sbi.adoc
Hi -- as discussed on the UNIX-Class Platform Specification Task Group mailing list [here](https://lists.riscv.org/g/tech-unixplatformspec/message/385), I would like to request SBI Implementation ID 5, please, for the Diosix project. Many thanks.
=> Add Diosix as SBI Implementation ID 5

Makefile, README.adoc, riscv-sbi.adoc
Added top-level makefile to build PDF/HTML documents and lots of other cleanups.
=> Top-level makefile and other cleanups

riscv-sbi.adoc
These are just some small changes I came up with when reading through the spec.  None of them are meant to change the meaning of the spec (at least, as I interpreted it) but there were some vague bits I thought it'd be best to clarify.  I didn't make it all the way through the spec, but I figured it'd be easier to just post this to start.
=> Some small changes

LICENSE
Address issue #75
Signed-off by: Jeff Scheel (jeff@riscv.org)
=> Add CC-BY-4.0 text into file

riscv-sbi.adoc
=> Fix a typo in SBI documentation

riscv-sbi.adoc
Sorry, the format of the patch in the maillist seems incorrect.
So I opens a PR here.
The discussion link is [here](https://lists.riscv.org/g/tech-unixplatformspec/topic/patch_1_1_proposal_to_add/84507846?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,84507846).
Thanks again.
=> [PATCH 1/1] Proposal to add Coffer to the SBI impl IDs list

riscv-sbi.adoc
Signed-off-by: Atish Patra <atishp@rivosinc.com>
=> Add a abbreviation table

riscv-sbi.adoc
Signed-off-by: Andrew Jones <ajones@ventanamicro.com>
=> HSM chapter grammar fixes

riscv-sbi.adoc
Clarify the error descriptions for some of the PMU functions.
Also opportunistically fix a couple grammar issues.
Signed-off-by: Andrew Jones <ajones@ventanamicro.com>
=> PMU chapter clarifications

README.adoc
Discussion: https://lists.riscv.org/g/tech-prs/message/37
=> Change reference design of SBI to a list of SBI impls included in specification

riscv-sbi.adoc
Add fixups to the SUSP chapter per the Architecture Review Committee's comments.
=> SUSP: fixups per ARC review

riscv-sbi.adoc
Add fixups to the SUSP chapter per the Architecture Review Committee's comments.
=> STA: fixups per ARC review

src/contributors.adoc
Zhouqi Jiang is my legal name for publications. Thanks!
=> Refer me as Luo Jia / Zhouqi Jiang <luojia@hust.edu.cn>

src/ext-mpxy.adoc
=> Fix typos in MPXY extension
