riscv-sbi.adoc

Since the doc has an .adoc extension it should follow asciidoc formatting rules, not mardkown (https://github.com/github/markup). I formatted this using the rules on http://asciidoc.org/userguide.html

Switch to asciidoc format

---

riscv-sbi.adoc

This draft is renamed from power management to Hart state management
extension and the function names are changed accordingly. It also
adds more description to each call and fixed some table issues.
Signed-off-by: Nick Kossifidis mick@ics.forth.gr

1st draft of Hart state management SBI extension.

---

riscv-sbi.adoc

This PR contains two minor fixes.
1. “Bit 32” here (1-origin) seems to be a bit off (a slight deviation from the RISC-V ISA Manual) and “Bit 31” (0-origin) is probably better.
2. A table in Hart State Management Extension contains a format error.

Minor fixes

---

riscv-sbi.adoc

Without an empty line, the two items are not rendered as a list but put inline with the previous line.

Fix list rendering in RFENCE Extension

---

riscv-sbi.adoc

Just a simple clarification of a sentence that's no longer fully correct with the next extensions.

Non-legacy calls all have return values

---

riscv-sbi.adoc

added note that the console functions are to be deprecated
added the function number tables for the (single-function) timer and IPI extensions
minor editorial changes

Console functions deprecated, Function number listings for Timer & IPI extensions

---

riscv-sbi.adoc

The SBI HFENCE VVMA calls use current VMID (in HGATP CSR) of calling
HART for flushing TLB enteries. This fact is not clearly evident in
current documentation of HFENCE VVMA calls hence this patch improves
documentation accordingly.

Clarify VMID consideration for SBI HFENCE VVMA calls

---

riscv-sbi.adoc

Made it clear that the function is deprecated and described the proper solution.

Fix few IPI related text

---

riscv-sbi.adoc

Adds SBI v0.2 compliant system reboot extension. It defines two functions:
1. sbi_reboot - A system reboot call with reboot type as parameter
2. sbi_shutdown - A system shutdown/poweroff call

Add system reset extension

---

riscv-sbi.adoc

FreeBSD does not do that and instead puts the syscall number in t0.

Using a7 for the syscall number is Linux-specific

---

riscv-sbi.adoc

Up to now the SBI specification does not define how unsupported EIDs and
FIDs shall be handled. Require returning error code SBI_ERR_NOT_SUPPORTED.
Signed-off-by: Heinrich Schuchardt <xypron.glpk@gmx.de>

Handling of unsupported EIDs and FIDs

---

riscv-sbi.adoc

Looks like a trivial typo, as this function does not take a `start_addr` argument.

Fix HART get status extension typo

---

riscv-sbi.adoc

This patch adds SBI performance monitoring unit (PMU) extension which
allows S-mode (or VS-mode) software to configure hardware (or firmware)
performance counters with help of M-mode (or HS-mode) software.

Add performance monitoring unit extension

---

riscv-sbi.adoc

Update 'a hierarchical topology groups' to 'hierarchical topology
groups'.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

Fix minor typo in HSM Extension

---

riscv-sbi.adoc

SBI specification calling convention can not refer to the syscall or
psABI calling convention because of the current implementation
FreeBSD/Linux precludes that.
Moreover, all the major SBI implementations  KVM, Xvisor) saves
all the registers (except a0 & a1) anyways.
Update the calling convention to reflect that.
Signed-off-by: Atish Patra <atishp@rivosinc.com>

Update the calling convention

---

riscv-sbi.adoc

The legacy SBI extensions (i.e. SBI v0.1) follow a slightly different
ABI where nothing is returned in a1 register and error code is returned
in a0 register. We need to document this fact correctly in the Legacy
extensions chapter.

Improve documentation of ABI followed by legacy SBI extensions

---

riscv-sbi.adoc

Add commas to improve the grammar in a couple error descriptions.
Suggested-by: Conor Dooley <conor.dooley@microchip.com>
Signed-off-by: Andrew Jones <ajones@ventanamicro.com>

HSM: Improve error description grammar

---

riscv-sbi.adoc

The Hart Software Services (HSS), used on PolarFire SoC, is based on OpenSBI, but OpenSBI comprises only a small fraction of the codebase, as the HSS only builds the select files that it needs due to heavy restrictions on code size.
It also does not run out of regular system memory, thereby avoiding issues with reserved-memory regions that affect many versions of OpenSBI.
Give it its own implementation ID so that supervisor mode software can differentiate it from regular OpenSBI.
Link: https://github.com/polarfire-soc/hart-software-services/

Add Hart Software Services SBI Implementation ID

---

riscv-sbi.adoc

Update the replacement for legacy console SBI functions
The legacy console SBI functions are now replaced by the new DBCN
extension. Update the out-of-date description for this.
Signed-off-by: Bin Meng <bmeng.cn@gmail.com>

Update the replacement for legacy console SBI functions

---

riscv-sbi.adoc

Correct 32-bit type values
HSM Hart Suspend Types, SRST System Reset Types and System Reset Reasons,
SUSP System Sleep Types are all 32-bit wide, so there is no such a value
that can be larger than 0xFFFFFFFF. Correct them.
Signed-off-by: Bin Meng <bmeng.cn@gmail.com>

Correct 32-bit type values

---

.github/workflows/build-doc.yml

This pull request integrates GitHub Actions to automate the build process of the specification document. The workflow is configured to trigger a build on each pull request and also supports manual build initiation via the workflow_dispatch event.
For releases, the workflow automatically captures the latest commit hash and utilizes it to uniquely name and tag the GitHub release.

Enable GitHub Actions for Automated Spec Build and Release

---

src/changelog.adoc
src/ext-experimental.adoc
src/ext-firmware.adoc
src/ext-nested-acceleration.adoc
src/ext-pmu.adoc
src/ext-steal-time.adoc
src/ext-vendor.adoc

There are usage of "is assumed to be" for normative statements. The meaning of it subjective and ambiguous. As the the intention was to use normative verbs anyways, lets just use "must" to provide more clarification.

Various cleanups

---

src/contributors.adoc

Because my `aist.go.jp` mail address is no longer accessible, this commit updates my contact information up to date.

Update contact information of mine

---

src/ext-legacy.adoc
src/ext-rfence.adoc

The two parameters are the start and size of the address range, not the start and end of the range.

Fix the wording for remote fence address ranges

---

src/ext-pmu.adoc

The counter start/stop function clearly states that snapshot shared memory area is only valid for the counters being stopped/started in the respective calls. That means the logical counter index modified must be relative to the counter base provided in the start/stop call. Add more clarification to avoid any ambiguity.

Clarify the logical counter index in the snapshot area.

---

src/ext-base.adoc

coreboot has had its own SBI since 2015, and
we are in the process of updating it.
oreboot is in the process of creating its own.

Add coreboot and oreboot extension IDs

---

src/ext-base.adoc

Support for bhyve/risc-v is not in the tree yet, but the work is in progress and it is able to boot riscv-guest already.

Add bhyve — FreeBSD-native hypervisor.

---

src/changelog.adoc
src/ext-time.adoc

Improve the phrasing on the clearing of the pending timer interrupt bit when timer interrupts are masked.
Additionally, clarify that this function can never fail.
CC: @atishp04 @jones-drew

Clarify the description of the `set_timer` function

---

src/ext-firmware-features.adoc

Allow supervisor software to request that pointer masking be enabled for S-mode. Supervisor software provides a lower bound on PMLEN, which abstracts away which specific pointer masking modes are supported.
This matches the pattern of the [proposed Linux API](https://lore.kernel.org/linux-riscv/20240814081437.956855-5-samuel.holland@sifive.com/) for enabling pointer masking in userspace.

Add POINTER_MASKING_PMLEN to the SBI FWFT extension

---

src/ext-sse.adoc

Previously "paramter", now "parameter".

Fix typo in Chapter 17.8 and 17.7: Read/Write software event attributes (SSE ext)

---

src/binary-encoding.adoc
src/ext-debug-console.adoc
src/ext-mpxy.adoc

As per the calling convention a1 will have sbiret.value on ecall return. However, the current specification describes an anlogous C structure describing as long. Some of the SBI extension may require an "unsigned long" data type instead of "long".
Relax the analgous C structure definition to allow that.
Fixes: https://github.com/riscv-non-isa/riscv-sbi-doc/issues/158

Clarify the sbiret.value

---

src/ext-debug-triggers.adoc

Typo fixes.
Also, clarify that all harts don't have one trig_max. Each has a separate trig_max.

DBTR typos

---

.github/workflows/build-pdf.yml
src/binary-encoding.adoc
src/ext-ipi.adoc
src/ext-rfence.adoc

hart_mask_base doesn't need to be valid unless bit0 of hart_mask is set, since the base isn't used independently. Clarify this to ensure implementations don't return SBI_ERR_INVALID_PARAM for invalid hart_mask_base when hart_mask isn't selecting it.

Clarify hart_mask_base requirements

---

src/ext-firmware-features.adoc
src/ext-pmu.adoc

We only use spaces in adoc files.

Replace tabs with spaces

---

src/ext-legacy.adoc

A public review suggestion[1] pointed out a grammar issue (is vs. are) and that it would be better to explicitly list which extensions replace the legacy functions.
Link: https://groups.google.com/a/groups.riscv.org/g/isa-dev/c/g1_vJUXAVZM [1]

Improve legacy extension deprecation notice
